### ISSUE TITLE
visibility error

### ISSUE THREAD

**Issue by ginihumer** [lineupjs/lineupjsx#24] opened 2021-01-26 09:29 UTC
* Release number or git hash: 4.0.0
 * Web browser version and OS: Google Chrome Version 87.0.4280.141 on Windows 10

### Steps to reproduce

 1. open react example in codepen: [https://codepen.io/sgratzl/pen/yvJpWQ](url)
 2. add `<LineUpJS.LineUpCategoricalColumnDesc column="cat" categories={cats} color="green" visible={false} />` in the beginning
 3. try to remove a column that would come after the previously added one

### Observed behavior
 * When adding the "visible={false}" property to a column description, it is not possible to delete any column that comes after this one without issue. When trying to delete such a column, it deletes the column after the selected one and sometimes there also occurs an error that causes the header to not render correctly anymore.
 * `Uncaught TypeError: Cannot read property 'getOrderLength' of null
    at e.summaryCategoricalStatsD (DirectRenderTasks.js:154)
    at e.summaryCategoricalStats (DirectRenderTasks.js:127)
    at Object.update (CategoricalCellRenderer.js:92)
    at t.updateHeader (RenderColumn.js:109)
    at e.updateHeader (EngineRanking.js:256)
    at e.updateHeader (ACellTableSection.js:49)
    at ACellAdapter.js:366
    at Array.forEach (<anonymous>)
    at e.t.recreate (ACellAdapter.js:364)
    at e.recreate (ACellTableSection.js:197)
e.summaryCategoricalStatsD @ DirectRenderTasks.js:154
e.summaryCategoricalStats @ DirectRenderTasks.js:127
update @ CategoricalCellRenderer.js:92
t.updateHeader @ RenderColumn.js:109
e.updateHeader @ EngineRanking.js:256
e.updateHeader @ ACellTableSection.js:49
(anonymous) @ ACellAdapter.js:366
t.recreate @ ACellAdapter.js:364
e.recreate @ ACellTableSection.js:197
e.updateAll @ EngineRanking.js:479
(anonymous) @ EngineRanking.js:145
(anonymous) @ debounce.js:27
setTimeout (async)
(anonymous) @ debounce.js:25
(anonymous) @ EngineRanking.js:156
apply @ dispatch.js:61
a @ AEventDispatcher.js:97
t.fireImpl @ AEventDispatcher.js:100
t.fire @ AEventDispatcher.js:74
e.remove @ Ranking.js:479
e.removeMe @ Column.js:253
onClick @ toolbar.js:155
u.onclick @ header.js:143
EngineRanking.js:299 Uncaught TypeError: Cannot read property 'width' of undefined
    at e.visibleRenderedWidth (EngineRanking.js:299)
    at e.updateShifts (EngineRanking.js:630)
    at e.updateSizer (ACellTableSection.js:126)
    at e.onScrolledHorizontally (ACellTableSection.js:170)
    at e.show (ACellTableSection.js:149)
    at MultiTableRowRenderer.js:54
    at Array.forEach (<anonymous>)
    at t.onScrolledHorizontally (MultiTableRowRenderer.js:48)
    at MultiTableRowRenderer.js:32
    at t.handle (scroll.js:55)`
 * Static or animated images showing the UI behavior
![image](https://user-images.githubusercontent.com/45741696/105826715-54257580-5fc1-11eb-833e-bef2e99ba893.png)

### Expected behavior
 * remove column

**Comment by sgratzl** [comment] 2022-07-26 02:03
duplicate of https://github.com/lineupjs/lineupjs/issues/404

**Closed as not planned by sgratzl** 2022-07-26 02:03 UTC
